doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            uuid: App\Infrastructure\Persistence\Doctrine\Type\UuidType

    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            App:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/PostgreSQL/Mapping'
                prefix: 'App\Domain\Entity'
                alias: App
